### ISSUE TITLE
Implementation edit items quantity of product service

### ISSUE THREAD

**Issue by PavelPavlovVC** [VirtoCommerce/vc-procurement-portal-theme#55]
### **AC**
1. GIVEN I am on the catalog page AND i have not empty active order  AND changing items quantity of product on value >1 in textbox  on selected product in tabular part AND textbox lost focus or press "Enter"
THEN in active order section must be changed items quantity in related product 
THEN in active order in part Total must be appear recalculated values: count items, subtotal, shippping, total.

2. GIVEN I am on the catalog page AND i have not empty active order  AND changing items quantity of product on value >1 in textbox  on selected product inactive order AND textbox lost focus or press "Enter"
THEN in related product in tabular part must be changed items quantity on changed value 
THEN in active order in part Total must be appear recalculated values: count items, subtotal, shippping, total.

3. GIVEN I am on the catalog page AND i have not empty active order AND changing items quantity of product on value =0 in textbox  on selected product in tabular part AND textbox lost focus or press "Enter"
THEN link 'remove' must be changed on button 'Plus' 
THEN on selected product in tabular part must be removed textbox for change quantity 
THEN active order section must take the form of an empty order 

4. GIVEN I am on the catalog page AND i have not empty active order  AND changing items quantity of product on value >1 in textbox  on selected product inactive order AND textbox lost focus or press "Enter"
THEN link 'remove' must be changed on button 'Plus'  in tabular part related product
THEN on selected product in tabular part must be removed textbox for change quantity
THEN active order section must take the form of an empty order 

**Input parameters**

- product id
- active order id
- count

**Result**
- if executed request successfully need refresh model

Detail:

using API storefront

**Comment by IgorisB** [comment]
A small note about the acceptance criteria format. We use GIVEN {context/prerequisites} WHEN {action} THEN {expected result} format. So your AC missing WHEN (action) part. I think, for example 1. AC should sound like this:

**GIVEN** I am on the catalog page AND i have not empty active order 
**WHEN** changing items quantity of product on value >1 in textbox on selected product in tabular part AND textbox lost focus or press "Enter"
**THEN** in active order section must be changed items quantity in related product AND in active order in part Total must be appear recalculated values: count items, subtotal, shippping, total.

**Comment by PavelPavlovVC** [comment]
Hi Igoris,

Agreed, it looks much more correct. Thank you, it will correct.


Best regards,
Pavlov. P




От: Igoris <notifications@github.com>
Отправлено: Monday, April 8, 2019 10:45 AM
Кому: VirtoCommerce/vc-procurement-portal-theme <vc-procurement-portal-theme@noreply.github.com>
Копия: Pavel Pavlov <ppa@virtoway.com>; Author <author@noreply.github.com>
Тема: Re: [VirtoCommerce/vc-procurement-portal-theme] Implementation edit items quantity of product service (#55)


A small note about the acceptance criteria format. We use GIVEN {context/prerequisites} WHEN {action} THEN {expected result} format. So your AC missing WHEN (action) part. I think, for example 1. AC should sound like this:

GIVEN I am on the catalog page AND i have not empty active order
WHEN changing items quantity of product on value >1 in textbox on selected product in tabular part AND textbox lost focus or press "Enter"
THEN in active order section must be changed items quantity in related product AND in active order in part Total must be appear recalculated values: count items, subtotal, shippping, total.
